### ISSUE TITLE
Update HsYAML version

### ISSUE THREAD

**Issue by vijayphoenix** [perlpunk/yaml-test-matrix#6]
A newer version [HsYAML-0.2.1.0](http://hackage.haskell.org/package/HsYAML) has been released and most probably https://matrix.yaml.io/ shows the performance of an older version of HsYAML.
So, please upgrade to the newer version of HsYAML.
If required, I will be happy to help

**Comment by perlpunk** [comment]
Unfortunately the matrix is a bit outdated at the moment in general.
The docker image creation was getting difficult to handle, so I'm currently creating new docker images that also can be used seperately.
See https://github.com/yaml/yaml-runtimes
But these docker images are not yet ready to be used for the matrix creation.
I hope I can work on that soon.
